### ISSUE TITLE
GitHub Setup

### ISSUE THREAD

**Issue by GustawB** [ZPP-MURMURAS/ZPP_Murmuras#1]
DoD:
- Requirement for someone to review PRs
- (Optional) GitHub action to compile tex to PDF
- Milestone definition
- Block pushes to Main
- Create "Way of Work": for our team

**Comment by nawiju** [comment]
Please give everyone permissions

**Comment by SzymonKozl** [comment]
create 'research' label pls

**Comment by GustawB** [comment]
Added requirement for PR review and all comments resolved
Added protection rules for the main branch (no direct commits, changes only by PRs)

**Comment by GustawB** [comment]
Added Milestones and assigned them to issues
Added labels and assigned them to issues

**Comment by SzymonKozl** [comment]
i like the "batchelor" name

**Comment by GustawB** [comment]
Added access for everyone
