### ISSUE TITLE
Analize possibilities for input data preprocessing.

### ISSUE THREAD

**Issue by GustawB** [ZPP-MURMURAS/ZPP_Murmuras#5]
Analize possibilities for input data preprocessing other than clustering.
DoD:
- Present results of research in notebook;
- If you end up with interesting papers, please summarize them and list them.

**Comment by SzymonKozl** [comment]
There are currently 3 problems with data provided in current format:

- single coupon data is split between several records
- large amount of duplicates
- noise created by irrelevant records (texts not being coupons' parts) 
I will look how to address all of them
